baseURL = "http://www.tokoro.me"
title = "TOKOROM BLOG"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "tokorom"

theme = "minimo"

rssuri = "atom.xml"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "ja"

[params.info]
description = "iOSアプリ開発者"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Yuta Tokoro"
startYear = "2012"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "2006-01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true

[params.sidebar]
enable = true
sticky = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = "tokorom@gmail.com"
facebook = "yuta.tokoro.7"
github = "tokorom"
gitlab = ""
instagram = ""
linkedin = ""
twitter = "tokorom"
telegram = ""
google_scholar = ""

[params.social.config]
platforms = ["github","twitter","facebook","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Blog"
weight = 10
identifier = "blog"
url = "/"
[[menu.main]]
name = "Twitter"
weight = 20
identifier = "twitter"
url = "https://twitter.com/tokorom/"
[[menu.main]]
name = "GitHub"
weight = 30
identifier = "repository"
url = "https://github.com/tokorom/"
[[menu.main]]
name = "Company"
weight = 40
identifier = "company"
url = "http://www.spinners.work/"
[[menu.main]]
name = "RSS"
weight = 50
identifier = "rss"
url = "/atom.xml"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
[languages.ja]
lang = "ja"
languageName = "Japanese"
weight = 1
