baseURL = "https://www.tokoro.me"
title = "TOKOROM BLOG"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "Copyright © tokorom. All Rights Reserved."

theme = "spinners"

disqusShortname = ""
googleAnalytics = "UA-2451574-4"

Paginate = 1000
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "ja"

[outputFormats.RSS]
baseName = "atom"

[params]
  author = "tokorom"
  description = "所のプログラミング関連技術ブログ"
  homepageImage = "/images/top_logo.png"
  share = true
  ogImage = "/images/ogp_image.png"
  favicon = "/images/favicon.ico"
  twitterAccount = "@tokorom"

  [params.social]
    rss = true
    # email = "example@example.com"
    # facebook = "https://facebook.com"
    # twitter = "https://twitter.com"
    # linkedin = "https://linkedin.com"
    # stack-overflow = "https://stackoverflow.com"
    # instagram = "https://stackoverflow.com"
    # github = "https://github.com"
    # weibo = "https://www.weibo.com"
    # medium = "https://medium.com"
    # pinterest = "https://pinterest.com"
    # reddit = "https://reddit.com"
    # gitlab = "https://gitlab.com"
    # mastodon = "https://mastodon.social"
    # keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = "okaidia"

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.instagram]
    disableInlineCSS = false

  [services.twitter]
    disableInlineCSS = true
