#!/bin/sh

if [ $# -ne 1 ]; then
  echo "Usage: copy-blog-to-spinners [entry_name]"
  exit 1
fi

ENTRYNAME=$1
SPINNERSDIR="${HOME}/develop/spinners/www.spinners.work"
POSTDIR="content/posts"
IMAGEDIR="content/images"

SOURCEENTRY="./${POSTDIR}/${ENTRYNAME}"
TARGETENTRY="${SPINNERSDIR}/${POSTDIR}/"

cp -r "${SOURCEENTRY}" "${TARGETENTRY}"
ret=$?
if [ $ret -eq 0 ]; then
  echo "Copied to ${TARGETENTRY}/${ENTRYNAME}"
fi

echo "${TARGETENTRY}/${ENTRYNAME}" | pbcopy
