#!/bin/sh

if [ $# -ne 1 ]; then
  echo "Usage: new [entry_name]"
  exit 1
fi

ENTRYNAME=$1

hugo new posts/${ENTRYNAME}.md

echo "content/posts/${ENTRYNAME}.md" | pbcopy
echo "content/posts/${ENTRYNAME}.md created and copied to clipboard"
